quarkus.hibernate-orm.database.generation=update
#debug
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true

#Tiingo Api Config
quarkus.rest-client.tiingo-api.url=https://api.tiingo.com/tiingo
tiingo.api.key=${TIINGO_API_KEY}

#ML serwis
quarkus.rest-client.ml-api.url=${ML_API_URL:http://localhost:8000}

quarkus.smallrye-openapi.info-title=Engineering Thesis - ETF Predictions API
quarkus.smallrye-openapi.info-version=1.0.0

%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true
