quarkus.hibernate-orm.database.generation=update
#debug
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true

#Tiingo Api Config
quarkus.rest-client.tiingo-api.url=https://api.tiingo.com/tiingo
tiingo.api.key=${TIINGO_API_KEY}